# Generated by Django 4.2.16 on 2024-09-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('grn', 'Green'), ('gry', 'Grey'), ('blu', 'Blue'), ('blk', 'Black'), ('yel', 'Yellow'), ('red', 'Red'), ('wht', 'White')], default='wht', max_length=3),
        ),
    ]
